#pragma once
void asianTown();
void asianTownShadowMap();
void fengShui();
void skybox1GL();
void skybox1RT();
void shadowMap();
void VulkanDemo();
void particles();
void animation();
void cornellBox1();
void cornellBox2();
void cornellBox3();
